name: Documentation Check
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16
    
    - name: Install dependencies
      run: npm ci

    - name: Run documentation check
      run: node index.js
      env: 
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
